services:
  # The Database
  postgis:
    image: postgis/postgis:15-3.3-alpine
    container_name: delivery-db
    environment:
      - POSTGRES_USER=teetotaler_admin
      - POSTGRES_PASSWORD=clean_code_only
      - POSTGRES_DB=delivery_mesh
    ports:
      - "5432:5432"

  # Redis for API Gateway Rate Limiting
  redis:
    image: redis:7-alpine
    container_name: delivery-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: delivery-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka for Event Streaming
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: delivery-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # The Catalog Microservice
  catalog-service:
    build: ../catalog-service
    container_name: catalog-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgis:5432/delivery_mesh
    depends_on:
      - postgis

  # The Order Microservice
  order-service:
    build: ../order-service
    container_name: order-app
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgis:5432/delivery_mesh
      - KAFKA_SERVERS=kafka:9093
    depends_on:
      - postgis
      - kafka

  # The API Gateway
  api-gateway:
    build: ../api-gateway
    container_name: gateway-app
    ports:
      - "8080:8080" # The only port exposed to your React app
    depends_on:
      - catalog-service